-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "defense" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "offense" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "price" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "salary" BIGINT NOT NULL DEFAULT 0;
